### PR TITLE
chore: use newspack-scripts

### PR DESCRIPTION
**Pull request by dkoo**
Update CI images and use `newspack-scripts` as implemented in https://github.com/Automattic/newspack-plugin/pull/1368 and https://github.com/Automattic/newspack-new-plugin-boilerplate/pull/3.

Also implements Dependabot, which was somehow missed during our last round adding it to all Newspack repos.

### How to test the changes in this Pull Request:

1. Make sure build and lint commands execute successfully:
   1. `npm start` (this is an alias for `npm ci && npm run watch`)
   2. `npm run build`
   3. `npm run lint:js`
   4. `npm run lint:scss`
2. Verify commitizen works by staging a change and running `npm run cm` – a prompt for a structured commit message should appear, just line on master
3. Verify the `commit-msg` hook does lint the commit message:
   1. reinstall the hook – `composer install`
   2. stage a change and try to commit with an unstructured commit message (e.g. `git commit -m "hehe"`) and observe it failing.

### CODE REVIEW

**Comment by dkoo** [comment]
@miguelpeixe I could use your help with a build error that I'm encountering with this branch. After installing `newspack-scripts` and moving to its configs, the `build` and `watch` commands fail to compile because of the extra babel config required by prebid.js. I get a bunch of errors from webpack like this:


```
ERROR in ./node_modules/prebid.js/modules/medianetRtdProvider.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: /Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-ads/node_modules/prebid.js/modules/medianetRtdProvider.js: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,

babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });

See https://babeljs.io/docs/en/options#filename for more information.
    at validateIfOptionNeedsFilename (/Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-ads/node_modules/@babel/core/lib/config/full.js:295:11)
    at /Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-ads/node_modules/@babel/core/lib/config/full.js:307:52
    at Array.forEach (<anonymous>)
    at validatePreset (/Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-ads/node_modules/@babel/core/lib/config/full.js:307:25)
    at loadPresetDescriptor (/Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-ads/node_modules/@babel/core/lib/config/full.js:314:3)
    at loadPresetDescriptor.next (<anonymous>)
    at recursePresetDescriptors (/Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-ads/node_modules/@babel/core/lib/config/full.js:114:30)
    at recursePresetDescriptors.next (<anonymous>)
    at recursePresetDescriptors (/Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-ads/node_modules/@babel/core/lib/config/full.js:137:32)
    at recursePresetDescriptors.next (<anonymous>)
 @ ./src/prebid/index.js 7:0-47

ERROR in ./node_modules/prebid.js/src/adapters/bidderFactory.js 212:10-21
export 'default' (imported as 'events') was not found in '../events.js' (module has no exports)
 @ ./node_modules/prebid.js/src/adapterManager.js 10:0-56 553:23-32
 @ ./node_modules/prebid.js/src/prebid.js 24:21-62
 @ ./src/prebid/index.js 1:0-29 9:0-17
```

Removing the `babel.config.js` file added by this PR allows webpack to complete the build, but then all `lint` commands fail due to a missing babel config file like this:

```
Parsing error: No Babel config file detected for /Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-ads/src/blocks/ad-unit/editor.js. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files
```

It's either one or the other. How do we resolve this conflict so we can both build _and_ lint?

**Comment by dkoo** [comment]
@miguelpeixe would 53f1d85 fix it? Since we're bundling prebid files with their own separate entrypoint, if we only apply the prebid.js Babel presets and plugins to that entrypoint, would that keep things separate enough?

**Comment by dkoo** [comment]
Rebased this branch, so please re-pull from the remote. In order to avoid [these errors](https://github.com/Automattic/newspack-ads/pull/286#issuecomment-1016947737), we're not using the instance of `@automattic/calypso-build` or `eslint` and its plugins from `newspack-scripts`.

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
Don't know exactly why, but `commitlint` is not being installed:

```
$ git commit -m "message"
✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
✔ Cleaning up temporary files...
.git/hooks/commit-msg: line 3: ./node_modules/.bin/commitlint: No such file or directory
```

**Comment by dkoo** [comment]
@miguelpeixe does e47387e fix it?

**Comment by miguelpeixe** [comment]
Using `composer install` wasn't updating the commit hook, I had to run `composer update` which fixed the hook and also updated my `composer.lock`. Should we update it for this PR?

The commit command is working now but it's also allowing me to commit with an unstructured commit message. Is your hook working properly?

**Comment by dkoo** [comment]
> The commit command is working now but it's also allowing me to commit with an unstructured commit message. Is your hook working properly?

Confirmed—the hook is not running. The following also outputs nothing:

```
﻿echo 'hehe' | ./node_modules/.bin/newspack-scripts commitlint
```

Updating `@wordpress/*` dependencies fixes this, but also causes the lint error mentioned above:

```
Parsing error: No Babel config file detected for /Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-ads/src/blocks/ad-unit/editor.js. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files
```

So we may as well use `newspack-scripts` for all dependencies (as with the other repos) and solve for the conflict with prebid.js's Babel plugin. 60932bf does this, but at the moment `build` and `watch` commands will fail due to this conflict. Tagging the PR as WIP until we figure this out.

**Comment by dkoo** [comment]
cc @adekbadek in case you have some insight here, too.

**Comment by miguelpeixe** [comment]
There's a solution to resolve the conflict between `@babel/preset-typescript` and `pbjsGlobals` plugin on Prebid.js' side.

[I sent a PR with the fix](https://github.com/prebid/Prebid.js/pull/7969). Meanwhile, I believe we should keep our own copy of this small babel plugin. WDYT @adekbadek @dkoo ?

**Comment by miguelpeixe** [comment]
- 2e42f5a4e45fab7621101a5630f3ec15e4a60d16 adds the local `pbjsGlobals.js` ignoring lint to preserve the original file structure.
- 840f9b711612342fed2559f4e66d4d1e6a754ac1 implements it to our webpack config, customizing [the original `.babelrc` provided by Prebid.js](https://github.com/prebid/Prebid.js/blob/master/.babelrc.js).

**Comment by dkoo** [comment]
I can confirm that @miguelpeixe's fix with the local `pbjsGlobals` file allows us to build and lint, and the Prebid JS is running on the front-end. Looks 👍 to me!

**Comment by adekbadek** [comment]
Adding a fix for https://github.com/Automattic/newspack-scripts/issues/50 in 1dcb33e6db9ab83dc1dc299101999cc88f6b2579

**Comment by adekbadek** [comment]
9b680d676c9765302ddbfd628cccdd957769adff should resolve the `commitlint` issues

**Review by adekbadek — APPROVED** [review]

**Pull request merged**
