### PR TITLE
feat: integrate ad refresh control plugin

### PR DESCRIPTION
**Pull request by miguelpeixe**
Integrate Ad Refresh Control plugin settings and allow its frontend scripts on AMP Plus.

Further details and test instructions are at https://github.com/Automattic/newspack-plugin/pull/1564

### CODE REVIEW

**Comment by yogeshbeniwal** [comment]
Can this also take care of scenario where publishers are filling unsold inventory with Adsense. Adsense ads refresh is not allowed as per policy.

**Comment by kmwilkerson** [comment]
@yogeshbeniwal If AdSense auto ads are used on the site, this plugin will not refresh them as it looks for GPT code only. If a publisher is filling unsold inventory with AdSense via GAM, it is the publisher's responsibility to block AdSense from refreshing by inputting the advertiser ID into the plugin settings.

**Review by dkoo — APPROVED** [review]
Tested locally and on a new test site—looks good to me!

**Comment by yogeshbeniwal** [comment]
@kmwilkerson What would be the advertiser ID for adsense in this case, f08c47fec0942fa0 is not accepted by plugin settings.

**Comment by kmwilkerson** [comment]
@yogeshbeniwal The advertiser ID for AdSense is `0`. I've added [an issue](https://github.com/Automattic/newspack-ads/issues/370) to automatically disable the refresh for this ID, but in the meantime you can input that value.

**Pull request merged**
