### PR TITLE
feat: add 1x1 to all size maps; deprecate AMP

### PR DESCRIPTION
**Pull request by dkoo**
Ensures that 1x1 is an allowed size for all ad units.

Also deprecates AMP support, which makes this PR a breaking change.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207127071414329

### CODE REVIEW

**Review by adekbadek — APPROVED** [review]

**Review by adekbadek — CHANGES_REQUESTED** [review]
Approved too quickly, I failed to notice failing tests: https://app.circleci.com/pipelines/github/Automattic/newspack-ads/2438/workflows/e2b7fedd-6419-4ab4-95ef-66c4395ccad9/jobs/9863

**Comment by dkoo** [comment]
Yeah, I saw the failing tests, too—not sure what that's about since it seems to have nothing to do with the changes. If I can get them to pass without further changes to non-test code, I'll merge

**Comment by dkoo** [comment]
This ended up being a bit of a rabbit hole. The failing tests all had to do with AMP-related code. Since our platform no longer officially supports AMP, I ended up removing all AMP-related code from the plugin + tests. This makes this PR a `BREAKING CHANGE` and therefore not as urgent.

**Review by adekbadek — APPROVED** [review]
> Also deprecates AMP support, which makes this PR a breaking change.

In order to trigger a major release update, don't forget to include `BREAKING CHANGE` in the commit message body when squashing.

**Pull request merged**
