### PR TITLE
feat(scaip): opt-out of integrated placements

### PR DESCRIPTION
**Pull request by miguelpeixe**
Allow users to disable the integrated placements for mid-content ad placement and re-enable SCAIP generated sidebars.

### How to test

1. Check-out this branch, https://github.com/Automattic/newspack-plugin/pull/1329 (checkbox fix) and visit the **Advertising -> Settings** wizard.
2. Make sure you have SCAIP plugin installed
2. Observe the new option on the **Post ad inserter settings** section for the use of legacy widgets
3. Confirm it is **enabled** by default
4. Visit the **Placements** wizard and observe that the post insertion placements are not available
5. Visit **Appearance -> Widgets** page and observe the standard SCAIP method is working as expected
6. Now disable the new option and observe the Post insertion placements are working as expected on the **Placements** wizard and the SCAIP widgets are gone

### CODE REVIEW

**Review by claudiulodro — APPROVED** [review]
LGTM, thanks for the speedy revision

**Comment by yogeshbeniwal** [comment]
@miguelpeixe This feature is saviour. Post insertion placement integration doesn't insert ads on AMP page. Disabling Use legacy widgets for ad placement and using SCAIP widget works well.

**Comment by miguelpeixe** [comment]
> During testing found that post insertion placement integration doesn't insert ads on AMP page.

I was not able to reproduce this. Did you try using this ad unit on a different placement, to confirm that it is an issue with the SCAIP integration?

**Comment by yogeshbeniwal** [comment]
@miguelpeixe Didn't go to that extent, but yeah used same ad unit for both scenarios, worked with SCAIP widget.

**Comment by yogeshbeniwal** [comment]
@miguelpeixe Works ok with latest version.

**Pull request merged**
