### PR TITLE
refactor: organize gam api objects

### PR DESCRIPTION
**Pull request by miguelpeixe**
This PR refactors the GAM API integration for better readability and scalability. It's now reorganized to be instantiated with an authentication method or session, e.g.:

```php
$api = new Api( 'service_account', $credentials );
```

### API Objects

Every GAM service is an extended [API object](https://github.com/Automattic/newspack-ads/blob/48fe4ae1febc5f04fd73a8fac53cd2856178049e/includes/providers/gam/api/class-api-object.php), which are instantiated by the `Api` constructor with the established session:

https://github.com/Automattic/newspack-ads/blob/48fe4ae1febc5f04fd73a8fac53cd2856178049e/includes/providers/gam/api/class-api.php#L106-L113

### Usage

The GAM Model class is now responsible for determining the authentication strategy, which allows the GAM API more agnostic in that sense:

https://github.com/Automattic/newspack-ads/blob/48fe4ae1febc5f04fd73a8fac53cd2856178049e/includes/providers/gam/class-gam-model.php#L71-L103

Through the `GAM_Model::get_api()` method the instantiated API is accessible along with its API objects, e.g.:

https://github.com/Automattic/newspack-ads/blob/48fe4ae1febc5f04fd73a8fac53cd2856178049e/includes/providers/gam/class-gam-model.php#L356-L363

## How to test

Unfortunately, I was not yet able to write tests because I couldn't find a good strategy for them. [Google Ads' library classes are all `final`](https://github.com/googleads/googleads-php-lib/blob/main/src/Google/AdsApi/AdManager/AdManagerSession.php) hence unable to mock. I accept suggestions on how to write them.

One possibility is to isolate the data processing logic into separate methods so they are accessible and detached from Google's library for unit testing but it's quite an effort and very likely to deteriorate code readability.

### Instructions

1. On a fresh site, check out this branch and https://github.com/Automattic/newspack-plugin/pull/2074
2. Connect to GAM using service account credentials
3. Make sure you see all existing ad units on the GAM configuration wizard
4. Create a new ad unit and confirm it was created
5. Edit the ad unit name and sizes and confirm it's updated
6. Delete the created ad unit and confirm it's deleted
7. Remove the service account credentials and confirm the ad units are available as "disconnected"
8. Connect with Google OAuth through the Connections wizard
9. Repeat steps 3 to 6

#### Header bidding

1. Enable header bidding with `define( 'NEWSPACK_ADS_EXPERIMENTAL_BIDDERS', true );` and confirm the steps from https://github.com/Automattic/newspack-ads/pull/310 works as expected

### CODE REVIEW

**Comment by leogermani** [comment]
* Make sure you see all existing ad units on the GAM configuration wizard :heavy_check_mark: 
* Create a new ad unit and confirm it was created :heavy_check_mark: 
* Edit the ad unit name and sizes and confirm it's updated :heavy_check_mark: 
* Delete the created ad unit and confirm it's deleted :x: 
* Remove the service account credentials and confirm the ad units are available as "disconnected" :heavy_check_mark: 
* Connect with Google OAuth through the Connections wizard :heavy_check_mark: 
* Repeat steps 3 to 6 :heavy_check_mark: :heavy_check_mark: :heavy_check_mark: :x: :heavy_check_mark: (same error on delete)

Everything worked fine except deleting (archiving) an unit when I got this error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Newspack_Ads\Providers\GAM\Api\Ad_Units::change_ad_unit_status() in /newspack-repos/newspack-ads/includes/providers/gam/class-gam-model.php:496
Stack trace:
#0 /newspack-repos/newspack-plugin/includes/configuration_managers/class-newspack-ads-configuration-manager.php(130): Newspack_Ads\Providers\GAM_Model::delete_ad_unit()
#1 /newspack-repos/newspack-plugin/includes/wizards/class-advertising-wizard.php(395): Newspack\Newspack_Ads_Configuration_Manager->delete_ad_unit()
```

Also, but this might be something specific to my env, I see this warning when I connect via oAuth:

Captura de tela de 2022-10-11 16-20-05

**Comment by miguelpeixe** [comment]
> Everything worked fine except deleting (archiving) an unit when I got this error (was it renamed to update_ad_unit_status ?)

This method was using the old API, e6aa37f06b8411db303e2c4e334773359ebf4e3f fixes it and adds error handling if the API is not available while attempting to delete.

**Review by leogermani — APPROVED** [review]
I confirm the latest change fixes the last test

**Comment by miguelpeixe** [comment]
Thank you for reviewing, @leogermani!

I'm going with a gradual implementation of tests, starting with the logic for building the `Creative` object here ae136f16c82612289e633f87327db8c30ce95a5b

**Comment by miguelpeixe** [comment]
> Also, but this might be something specific to my env, I see this warning when I connect via oAuth:
> 
> Captura de tela de 2022-10-11 16-20-05

dc478d9f5b60e506e669f5c85b724be3f0a8354a also fixes this issue. The request right after connection (either OAuth or Service Account) doesn't yet have the network code in order to create the default targeting keys. The next request will have it so there's no need to throw an error, just ignore it and allow the next request to satisfy this feature.

**Pull request merged**
